[project-run]
; command="$(VIM_FILEPATH)"
command=make dev
output=terminal
cwd=$(VIM_ROOT)
save=2


[project-build]
command=make build
output=quickfix
cwd=$(VIM_ROOT)
save=2

[project-test]
command:make=make test
command:c,cpp=bash -c 'if [ -f CMakeLists.txt ]; then cmake --build build --target test; else echo "Nenhum test configurado"; fi'
cwd=$(VIM_ROOT)
save=2

[cmake-configure]
command=cmake -B build -DCMAKE_BUILD_TYPE=Debug
output=quickfix
cwd=$(VIM_ROOT)
save=2
